jobs:
  - name: script-0y021
    type: runSh
    serial: true
    steps:
      - GET: sample-script3
      - TASK:
        - script: pwd
        - script: ./GET/sample-script2/sample-script2/echo.sh
  - name: script-0y022
    type: runSh
    serial: true
    steps:
      - GET: sample-script3
      - TASK:
        - script: ls
        - script: ./GET/sample-script2/sample-script2/echo.sh
  - name: script-0y023
    type: runSh
    serial: true
    steps:
      - GET: sample-script3
      - TASK:
        - script: ps
        - script: ./GET/sample-script2/sample-script2/echo.sh
