jobs:
  - name: script-0y101
    type: runSh
    #serial: true
    steps:
      - IN: script-test
      - IN: triggerscript
      - TASK:
        - script: pwd
        - script: ./IN/script-test/script-test/echo.sh
 # - name: script-0y101
  #  type: runSh
    #serial: true
  #  steps:
   #   - GET: sample-script1
    #  - GET: triggertest2
     # - TASK:
      #  - script: ls
       # - script: ./GET/sample-script/sample-script/echo.sh
  #- name: script-0y102
   # type: runSh
    #serial: true
    #steps:
     # - GET: sample-script1
      #- TASK:
       # - script: ps
      #  - script: ./GET/sample-script/sample-script/echo.sh
