jobs:
  - name: script-0x016
    type: runSh
    steps:
      - GET: sample-script
      - TASK:
        - script: ps
        - script: ls3
        - script: ./GET/sample-script/sample-script/echo.sh
