jobs:
  - name: script-0x013
    type: runSh
    steps:
      - GET: sample-script
      - TASK:
        - script: ps2
        - script: ls2
        - script: ./GET/sample-script/sample-script/echo.sh
